version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "portfolio-id"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-5h1u4aqp83b5"
s3_prefix = "portfolio-id"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
